/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AdminCapabilityConfigDTO
 */
export interface AdminCapabilityConfigDTO {
    /**
     * If true, this capability configuration grant access to all capabilities.
     * @type {boolean}
     * @memberof AdminCapabilityConfigDTO
     */
    'allCapabilitiesAccess'?: boolean;
    /**
     * A list of capabilities associated with the capability configuration.
     * @type {Array<string>}
     * @memberof AdminCapabilityConfigDTO
     */
    'capabilities'?: Array<string>;
}

