/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RelatedAnalyticObjectDTO } from './related-analytic-object-dto';
import { SecurableDimensionDTO } from './securable-dimension-dto';
import { SecurablePropertyDTO } from './securable-property-dto';

/**
 * 
 * @export
 * @interface AnalyticObjectDTO
 */
export interface AnalyticObjectDTO {
    /**
     * The unique ID of the analytic object.
     * @type {string}
     * @memberof AnalyticObjectDTO
     */
    'analyticObjectId'?: string;
    /**
     * An identifiable name to display in Visier, such as \"Employee\".
     * @type {string}
     * @memberof AnalyticObjectDTO
     */
    'displayName'?: string;
    /**
     * The analytic object type.
     * @type {string}
     * @memberof AnalyticObjectDTO
     */
    'objectType'?: AnalyticObjectDTOObjectTypeEnum;
    /**
     * The analytic objects related to the data security object.
     * @type {Array<RelatedAnalyticObjectDTO>}
     * @memberof AnalyticObjectDTO
     */
    'relatedObjects'?: Array<RelatedAnalyticObjectDTO>;
    /**
     * All available properties from the data security object and its related analytic objects that you can configure data access for.
     * @type {Array<SecurablePropertyDTO>}
     * @memberof AnalyticObjectDTO
     */
    'securableProperties'?: Array<SecurablePropertyDTO>;
    /**
     * A list of dimensions that are available to define population access filters in the permission.
     * @type {Array<SecurableDimensionDTO>}
     * @memberof AnalyticObjectDTO
     */
    'securableDimensions'?: Array<SecurableDimensionDTO>;
}

type AnalyticObjectDTOObjectTypeEnum = 'Event' | 'Subject' | 'BusinessOutcomeOverlay' | 'PlanOrBudgetOverlay' | 'ExternalBenchmark' | 'VisierBenchmark' | 'UsageOverlay' | 'OtherOverlay' | 'InternalComparison' | 'PlanAnalyticObject'


