/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CapabilityDTO
 */
export interface CapabilityDTO {
    /**
     * A description of the capability.
     * @type {string}
     * @memberof CapabilityDTO
     */
    'description'?: string;
    /**
     * The unique name of the capability.
     * @type {string}
     * @memberof CapabilityDTO
     */
    'name'?: string;
    /**
     * An identifiable capability name to display in Visier, such as \"Schedule Analysis\".
     * @type {string}
     * @memberof CapabilityDTO
     */
    'displayName'?: string;
}

