/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ContentPackageDTO
 */
export interface ContentPackageDTO {
    /**
     * A description of the content package.
     * @type {string}
     * @memberof ContentPackageDTO
     */
    'description'?: string;
    /**
     * The unique ID of the content package.
     * @type {string}
     * @memberof ContentPackageDTO
     */
    'contentPackageId'?: string;
    /**
     * An identifiable content package name to display in Visier, such as \"Talent Acquisition Core Content\".
     * @type {string}
     * @memberof ContentPackageDTO
     */
    'displayName'?: string;
}

