/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InheritedAccessConfigDTO } from './inherited-access-config-dto';
import { MemberFilterConfigDTO } from './member-filter-config-dto';
import { PropertySetConfigDTO } from './property-set-config-dto';

/**
 * 
 * @export
 * @interface DataSecurityProfileDTO
 */
export interface DataSecurityProfileDTO {
    /**
     * The analytic object ID associated with the data security profile.
     * @type {string}
     * @memberof DataSecurityProfileDTO
     */
    'analyticObjectId'?: string;
    /**
     * The property set configuration that defines which properties and access level to allow for each filtered record.
     * @type {PropertySetConfigDTO}
     * @memberof DataSecurityProfileDTO
     */
    'propertySetConfig'?: PropertySetConfigDTO;
    /**
     * The flag for giving all access to data points when creating a population.
     * @type {boolean}
     * @memberof DataSecurityProfileDTO
     */
    'allDataPointAccess'?: boolean;
    /**
     * The member filter configurations that defines the population.
     * @type {Array<MemberFilterConfigDTO>}
     * @memberof DataSecurityProfileDTO
     */
    'memberFilterConfigs'?: Array<MemberFilterConfigDTO>;
    /**
     * A list of objects representing the inherited access configurations associated with the data security profile.  By default all related objects of a top level analytic object will inherit access.  To remove access to a related analytic object, add it to the list of inherited access configurations with removeAccess: true.  To add custom filters to a related analytic object, add the analytic object to the list of inherited access configurations and then add the custom filters to its list of member filter configurations.
     * @type {Array<InheritedAccessConfigDTO>}
     * @memberof DataSecurityProfileDTO
     */
    'inheritedAccessConfigs'?: Array<InheritedAccessConfigDTO>;
}

