/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DynamicDimensionFilterDTO } from './dynamic-dimension-filter-dto';
import { StaticDimensionFilterDTO } from './static-dimension-filter-dto';

/**
 * 
 * @export
 * @interface DimensionFilterDTO
 */
export interface DimensionFilterDTO {
    /**
     * 
     * @type {StaticDimensionFilterDTO}
     * @memberof DimensionFilterDTO
     */
    'staticDimensionFilter'?: StaticDimensionFilterDTO;
    /**
     * 
     * @type {DynamicDimensionFilterDTO}
     * @memberof DimensionFilterDTO
     */
    'dynamicDimensionFilter'?: DynamicDimensionFilterDTO;
}

