/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserPropertyDTO } from './user-property-dto';

/**
 * 
 * @export
 * @interface DynamicPropertyMappingDTO
 */
export interface DynamicPropertyMappingDTO {
    /**
     * The hierarchy property ID.
     * @type {string}
     * @memberof DynamicPropertyMappingDTO
     */
    'hierarchyPropertyId'?: string;
    /**
     * The user property.
     * @type {UserPropertyDTO}
     * @memberof DynamicPropertyMappingDTO
     */
    'userProperty'?: UserPropertyDTO;
}

