/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContentPackageDTO } from './content-package-dto';

/**
 * 
 * @export
 * @interface GetContentPackagesAPIResponseDTO
 */
export interface GetContentPackagesAPIResponseDTO {
    /**
     * A list of objects representing the available content packages.
     * @type {Array<ContentPackageDTO>}
     * @memberof GetContentPackagesAPIResponseDTO
     */
    'contentPackages'?: Array<ContentPackageDTO>;
}

