/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionDTO } from './permission-dto';

/**
 * List of available permissions
 * @export
 * @interface GetPermissionsAPIResponseDTO
 */
export interface GetPermissionsAPIResponseDTO {
    /**
     * A list of objects representing the available permissions.
     * @type {Array<PermissionDTO>}
     * @memberof GetPermissionsAPIResponseDTO
     */
    'permissions'?: Array<PermissionDTO>;
}

