/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CapabilityDTO } from './capability-dto';

/**
 * 
 * @export
 * @interface GetCapabilitiesAPIResponseDTO
 */
export interface GetCapabilitiesAPIResponseDTO {
    /**
     * A list of objects representing the available capabilities.
     * @type {Array<CapabilityDTO>}
     * @memberof GetCapabilitiesAPIResponseDTO
     */
    'capabilities'?: Array<CapabilityDTO>;
}

