/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface HierarchyPropertyDTO
 */
export interface HierarchyPropertyDTO {
    /**
     * The hierarchy property ID.
     * @type {string}
     * @memberof HierarchyPropertyDTO
     */
    'hierarchyPropertyId'?: string;
    /**
     * An identifiable hierarchy property name to display in Visier, such as \"Name Property\".
     * @type {string}
     * @memberof HierarchyPropertyDTO
     */
    'displayName'?: string;
}

