/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DimensionFilterDTO } from './dimension-filter-dto';

/**
 * 
 * @export
 * @interface MemberFilterConfigDTO
 */
export interface MemberFilterConfigDTO {
    /**
     * A list of objects representing the dimension filters associated with the member filter configuration.  A dimension filter can be either a static or dynamic dimension filter.
     * @type {Array<DimensionFilterDTO>}
     * @memberof MemberFilterConfigDTO
     */
    'dimensionFilters'?: Array<DimensionFilterDTO>;
}

