/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionFailureDTO } from './permission-failure-dto';
import { PermissionSuccessDTO } from './permission-success-dto';

/**
 * 
 * @export
 * @interface PermissionBulkOperationResponseDTO
 */
export interface PermissionBulkOperationResponseDTO {
    /**
     * The successfully processed permissions.
     * @type {Array<PermissionSuccessDTO>}
     * @memberof PermissionBulkOperationResponseDTO
     */
    'successes'?: Array<PermissionSuccessDTO>;
    /**
     * The permissions that did not process and any relevant error information.
     * @type {Array<PermissionFailureDTO>}
     * @memberof PermissionBulkOperationResponseDTO
     */
    'failures'?: Array<PermissionFailureDTO>;
}

