/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PermissionErrorDTO
 */
export interface PermissionErrorDTO {
    /**
     * Error message
     * @type {string}
     * @memberof PermissionErrorDTO
     */
    'message'?: string;
    /**
     * A root cause identifier that allows Visier to determine the source of the problem.
     * @type {string}
     * @memberof PermissionErrorDTO
     */
    'rci'?: string;
}

