/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AdminCapabilityConfigDTO } from './admin-capability-config-dto';
import { DataSecurityProfileDTO } from './data-security-profile-dto';
import { RoleModulesConfigDTO } from './role-modules-config-dto';

/**
 * 
 * @export
 * @interface PermissionDTO
 */
export interface PermissionDTO {
    /**
     * A user-defined description of the permission.
     * @type {string}
     * @memberof PermissionDTO
     */
    'description'?: string;
    /**
     * The unique identifier associated with the permission.
     * @type {string}
     * @memberof PermissionDTO
     */
    'permissionId'?: string;
    /**
     * An identifiable permission name to display in Visier, such as \"Diversity Access\".
     * @type {string}
     * @memberof PermissionDTO
     */
    'displayName'?: string;
    /**
     * A list of objects representing the data security profile configurations associated with the permission.
     * @type {Array<DataSecurityProfileDTO>}
     * @memberof PermissionDTO
     */
    'dataSecurityProfiles'?: Array<DataSecurityProfileDTO>;
    /**
     * The capability configuration associated with the permission.
     * @type {AdminCapabilityConfigDTO}
     * @memberof PermissionDTO
     */
    'adminCapabilityConfig'?: AdminCapabilityConfigDTO;
    /**
     * The role modules configuration associated with the permission.
     * @type {RoleModulesConfigDTO}
     * @memberof PermissionDTO
     */
    'roleModulesConfig'?: RoleModulesConfigDTO;
}

