/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionDTO } from './permission-dto';

/**
 * 
 * @export
 * @interface PermissionsListDTO
 */
export interface PermissionsListDTO {
    /**
     * The list of permissions that will be created or updated
     * @type {Array<PermissionDTO>}
     * @memberof PermissionsListDTO
     */
    'permissions'?: Array<PermissionDTO>;
}

