/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionErrorDTO } from './permission-error-dto';

/**
 * 
 * @export
 * @interface PermissionFailureDTO
 */
export interface PermissionFailureDTO {
    /**
     * The unique identifier associated with the permission.
     * @type {string}
     * @memberof PermissionFailureDTO
     */
    'permissionId'?: string;
    /**
     * An identifiable permission name to display in Visier, such as \"Diversity Access\".
     * @type {string}
     * @memberof PermissionFailureDTO
     */
    'displayName'?: string;
    /**
     * The error associated with the failure.
     * @type {PermissionErrorDTO}
     * @memberof PermissionFailureDTO
     */
    'error'?: PermissionErrorDTO;
}

