/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PropertyAccessConfigDTO } from './property-access-config-dto';

/**
 * 
 * @export
 * @interface PropertySetConfigDTO
 */
export interface PropertySetConfigDTO {
    /**
     * A list of objects representing the property access configuration associated with the property set configuration.
     * @type {Array<PropertyAccessConfigDTO>}
     * @memberof PropertySetConfigDTO
     */
    'propertyAccessConfigs'?: Array<PropertyAccessConfigDTO>;
}

