/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PropertyAccessConfigDTO
 */
export interface PropertyAccessConfigDTO {
    /**
     * The property ID associated with the property access configuration.
     * @type {string}
     * @memberof PropertyAccessConfigDTO
     */
    'propertyId'?: string;
    /**
     * The analytic object ID of the property.
     * @type {string}
     * @memberof PropertyAccessConfigDTO
     */
    'analyticObjectId'?: string;
    /**
     * The path to the analytic object reference or empty if the configuration is not a reference.
     * @type {Array<string>}
     * @memberof PropertyAccessConfigDTO
     */
    'analyticObjectReferencePaths'?: Array<string>;
    /**
     * The access level of the property. Valid values are: Aggregate, Sensitive
     * @type {string}
     * @memberof PropertyAccessConfigDTO
     */
    'accessLevel'?: PropertyAccessConfigDTOAccessLevelEnum;
}

type PropertyAccessConfigDTOAccessLevelEnum = 'None' | 'Aggregate' | 'Detailed'


