/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RelatedAnalyticObjectDTO
 */
export interface RelatedAnalyticObjectDTO {
    /**
     * The analytic object ID.
     * @type {string}
     * @memberof RelatedAnalyticObjectDTO
     */
    'analyticObjectId'?: string;
    /**
     * An identifiable analytic object name to display in Visier, such as \"Recognition\".
     * @type {string}
     * @memberof RelatedAnalyticObjectDTO
     */
    'displayName'?: string;
}

