/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RoleModulesConfigDTO
 */
export interface RoleModulesConfigDTO {
    /**
     * A list of content packages IDs associated with the role modules configuration.
     * @type {Array<string>}
     * @memberof RoleModulesConfigDTO
     */
    'contentPackageIds'?: Array<string>;
}

