/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HierarchyPropertyDTO } from './hierarchy-property-dto';

/**
 * 
 * @export
 * @interface SecurableDimensionDTO
 */
export interface SecurableDimensionDTO {
    /**
     * The dimension ID.
     * @type {string}
     * @memberof SecurableDimensionDTO
     */
    'dimensionId'?: string;
    /**
     * An identifiable dimension name to display in Visier, such as \"Contract Type\".
     * @type {string}
     * @memberof SecurableDimensionDTO
     */
    'displayName'?: string;
    /**
     * A list of analytic object IDs.
     * @type {Array<string>}
     * @memberof SecurableDimensionDTO
     */
    'analyticObjectIds'?: Array<string>;
    /**
     * The list of hierarchies you can map to a user in a permission\'s dynamic filter.
     * @type {Array<HierarchyPropertyDTO>}
     * @memberof SecurableDimensionDTO
     */
    'hierarchyProperties'?: Array<HierarchyPropertyDTO>;
}

