/*
Visier Permission Management APIs

Visier APIs for managing permissions within an organization

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserPropertyDTO
 */
export interface UserPropertyDTO {
    /**
     * The user property name.
     * @type {string}
     * @memberof UserPropertyDTO
     */
    'name'?: string;
}

